# # URLs for the API
# The purpose of this file is to generate the needed urlpatterns to serve the API.
# Django REST Framework provides a built in router to make constructing the URLs easy.
# See 
# [http://www.django-rest-framework.org/api-guide/routers/](http://www.django-rest-framework.org/api-guide/routers/)
# for more details

from django.conf.urls import include, url
from rest_framework import routers

from sups.viewsets import SupViewSet

# `router` generates the url patterns for us.
router = routers.DefaultRouter()

# Registers the `SupViewSet` at `/sups`.
# Since our api.urls are included in the `conf.urls` at `api/`
# all routes handled but `SupViewSet` are at `/api/sups`. This includes:
#
# * `GET /api/sups/` - List of all sups
# * `GET /api/sups/:id/` - Get a specific sup
# * `POST /api/sups/` - Create a new sup
# * `PUT /api/sups/:id/` - Update a specific sup
# * `DELETE /api/sups/:id` - Delete a specific sup
router.register(r'sups', SupViewSet)

# Inlude the url patterns generated by `router` in our `urlpatterns` list.
# Django looks for the variable urlpatterns by default when you include a 
# Django apps urls. See `conf.urls` for usage of this file.
urlpatterns = [
    url(r'^', include(router.urls)), 
]

# ## Related
# * [conf.urls](../conf/urls.py.html) - Where this file is getting used.
# * [sups.viewsets](../sups/viewsets.py.html) - Implementation of the `SupViewSet`
